# Generated by Django 5.1.6 on 2025-02-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    def add_data(apps, schema_editor):
        vertical = apps.get_model('users', 'Vertical')
        plan = apps.get_model('users', 'Plan')

        poder = vertical.objects.create(id=1, name="Poder")
        tributos = vertical.objects.create(id=2, name="Tributos")
        saude = vertical.objects.create(id=3, name="Saúde")
        energia = vertical.objects.create(id=4, name="Energia")
        trabalhista = vertical.objects.create(id=5, name="Trabalhista")

        plan.objects.create(id=1, name="JOTA Info", price=0.0)

        pro = plan.objects.create(id=2, name="JOTA PRO", price=75.80)
        pro.verticals.add(poder, tributos, saude, energia, trabalhista)

    dependencies = [
        ('users', '0002_remove_plan_vertical_plan_verticals'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
